### ISSUE TITLE
Support for CHTTP

### ISSUE THREAD

**Issue by ghost** [BadgerCode/TTT-Low-Karma-Kick-Notification#1]
Would it be possible to add CHTTP support like Damagelogs? I don't understand about proxies haha!

**Comment by BadgerCode** [comment]
Added in #2 

Could you download it and give it a test if possible?

You can get the files on the [Support_CHTTP branch](https://github.com/BadgerCode/TTT-Low-Karma-Kick-Notification/tree/Support_CHTTP)

https://github.com/BadgerCode/TTT-Low-Karma-Kick-Notification/archive/refs/heads/Support_CHTTP.zip

**Comment by ghost** [comment]
I tested it and it is working, thank you!

**Comment by BadgerCode** [comment]
Cheers!
